#--------------------------------------------------------------------------------------------------
# Configuration script for use with continuous integration service travis-ci.org
#

notifications:
  email:
    - covise-commits@listserv.uni-stuttgart.de

sudo: false
dist: trusty

language: cpp
os:
    - linux
    - osx

env:
    matrix:
        - APP="covise" BUILD_TYPE="Debug"
        - APP="covise" BUILD_TYPE="Release"
        - APP="cover"  BUILD_TYPE="Debug"
        - APP="cover"  BUILD_TYPE="Release"

matrix:
    exclude:
        # FIXME
        - os: osx

addons:
    apt:
        packages:
            - libboost-all-dev
            - libglew-dev
            - libxi-dev
            - libxmu-dev
            - freeglut3-dev
            - qttools5-dev
            - qtscript5-dev
            - libqt5scripttools5
            - libqt5svg5-dev
            - libqt5opengl5-dev
            - libqt5webkit5-dev
            - libxerces-c-dev
            - libpng12-dev
            - libopenscenegraph-dev
            - libosgearth-dev
            - libavcodec-dev
            - libswscale-dev

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall xerces-c ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall glew ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall giflib ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall libpng ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall libtiff ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall freetype ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall boost ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall python3 ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall qt5 ;fi

script:

    - export COVISE_CMAKE_OPTIONS=-DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - export COVISE_CMAKE_OPTIONS="-DCOVISE_BUILD_RENDERER:BOOL=OFF "$COVISE_CMAKE_OPTIONS
    - if [ "$APP" = "cover" ];  then export COVISE_CMAKE_OPTIONS="-DCOVISE_BUILD_ONLY_COVER_PREREQ:BOOL=ON "$COVISE_CMAKE_OPTIONS; fi
    - export COVISE_CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX="${HOME}"/install "$COVISE_CMAKE_OPTIONS
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export ARCHSUFFIX=macos; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export ARCHSUFFIX=tahr; fi
    - if [ "${BUILD_TYPE}" != "Debug" ]; then export ARCHSUFFIX=${ARCHSUFFIX}opt; fi
    - source .covise.sh
    - if [ "$APP" = "covise" ]; then make covise -j6; fi
    - if [ "$APP" = "cover" ];  then unset PYTHON_HOME; fi
    - if [ "$APP" = "cover" ]; then make -j6; fi
