[plugin]
3dm = ["3dm", "rhino"]
Trajectories = ["bcrtf", "crtf"]
Bore = ["bcsv"]
GPS = ["gpx"]
Amber = ["top", "trj"]
LamurePointCloud = ["bvh"]
IFC = ["ifc", "stp", "step"]
CsvPointCloud = ["csv", "oct"]
GLTF = ["glb", "gltf"]
BPA = ["bpadxf", "nfi", "nfix"]
Bullet = ["bullet"]
CADCv3D = ["cgl"]
CNC = ["gcode"]
DEMOA = ["dani", "dsim"]
Earth = ["earth"]
JTOpen = ["jt"]
Midi = ["mid"]
Molecules = ["via", "vim", "vis"]
OpenScenario = ["xosc"]
Particles = ["chkpt", "coord", "crist", "indent", "particle"]
PCL = ["pcd"]
PLMXML = ["plmxml", "xml"]
#Point = ["xyz"]
#PointModel = ["pts", "xyz"]
PointCloud = ["c2m", "pts", "ptsb", "ptx", "xyz", "e57"]
Script = ["js", "qs"]
starDust = ["startDust", "stardust"]
StereoVideoPlayer = ["avi", "mov", "mp4", "wmv"]
TrafficSimulation = ["xodr"]
ThreeDTK = ["oct"]
Volume = ["avf", "nii", "nii.gz", "rvf", "tif", "tiff", "xvf", "dcm", "dicomdir"]
VRAnim = ["dyn", "geoall", "sensor", "str"]
Vrml97 = ["wrl", "wrl.gz", "wrz", "x3d", "x3dv"]

[osg]
# add filters for the osg_db plugins supporting any of these formats
extensions = ["wrl", "osg", "ive", "osgb", "osgt", "osgx", "obj", "stl", "ply", "iv", "dxf", "3ds", "flt", "dae", "md2", "geo", "bvh", "fbx"]
